[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projectdavid_common"
version = "0.62.0"
description = "Common shared custom packages"
readme = "README.md"
authors = [
  { name = "Francis N.", email = "engineering@projectdavid.co.uk" }
]
license = { text = "MIT" }
keywords = ["shared", "internal", "utilities", "schemas"]
requires-python = ">=3.10"

dependencies = [
  "pydantic",
  "typing_extensions",
  "httpx",
  "python-dotenv",
  "sqlalchemy>=2.0"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black==24.1.1",
  "isort==5.13.2",
  "bandit==1.7.7",
  "mypy>=1.0",
  "pre-commit",
]

[project.urls]
Homepage = "https://github.com/project-david-ai/entities-common"
Documentation = "https://docs.projectdavid.co.uk/docs"
Changelog = "https://github.com/project-david-ai/entities-common/blob/main/CHANGELOG.md"

[project.scripts]
projectdavid_common-api = "projectdavid_common.main:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["projectdavid_common", "projectdavid_common.*"]

[tool.setuptools.dynamic]
version = { attr = "projectdavid_common.__version__.__version__" }

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [".venv", ".git", "__pycache__", "build", "dist"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["tests/"]
